// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi5QF3io5mT45vnqzrFpaJQrT6VIOYZHU',
    appId: '1:968515291575:web:def26b772dec4e00824032',
    messagingSenderId: '968515291575',
    projectId: 'taskflow-955df',
    authDomain: 'taskflow-955df.firebaseapp.com',
    databaseURL: 'https://taskflow-955df-default-rtdb.firebaseio.com',
    storageBucket: 'taskflow-955df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2D5nZIdsa-GLRtGIBtg5olDg584JdXKk',
    appId: '1:968515291575:android:a1c95b3821cb8712824032',
    messagingSenderId: '968515291575',
    projectId: 'taskflow-955df',
    databaseURL: 'https://taskflow-955df-default-rtdb.firebaseio.com',
    storageBucket: 'taskflow-955df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20GCiTUW0irjgmiMo7izYsdpLQhq3XaY',
    appId: '1:968515291575:ios:04e64eb2ff8ba363824032',
    messagingSenderId: '968515291575',
    projectId: 'taskflow-955df',
    databaseURL: 'https://taskflow-955df-default-rtdb.firebaseio.com',
    storageBucket: 'taskflow-955df.firebasestorage.app',
    iosBundleId: 'com.roushan.taskflow.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC20GCiTUW0irjgmiMo7izYsdpLQhq3XaY',
    appId: '1:968515291575:ios:04e64eb2ff8ba363824032',
    messagingSenderId: '968515291575',
    projectId: 'taskflow-955df',
    databaseURL: 'https://taskflow-955df-default-rtdb.firebaseio.com',
    storageBucket: 'taskflow-955df.firebasestorage.app',
    iosBundleId: 'com.roushan.taskflow.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi5QF3io5mT45vnqzrFpaJQrT6VIOYZHU',
    appId: '1:968515291575:web:c3efdd1aa169a886824032',
    messagingSenderId: '968515291575',
    projectId: 'taskflow-955df',
    authDomain: 'taskflow-955df.firebaseapp.com',
    databaseURL: 'https://taskflow-955df-default-rtdb.firebaseio.com',
    storageBucket: 'taskflow-955df.firebasestorage.app',
  );
}
